spring:
  application:
    name: student-course-registration-portal
  
  datasource:
    url: jdbc:mysql://localhost:3306/student_registration?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /

# Custom JWT configuration
app:
  jwt:
    secret: 9a67638673a382838a838a838f838f838f838f838f838f838f838f838f838f83
    expiration-ms: 86400000 # 24 Hours

# Logging
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    com.saas.portal: DEBUG
